workspace:
  name: oasm
  edition: "2021"
  resolver: "2"

  members:
    - compiler
    - runtime/daemon
    - ui/rust_ui

  common_dependencies:
    log: "0.4"
    env_logger: "0.11"
    anyhow: "1.0"
    serde:
      version: "1.0"
      features: ["derive"]
    serde_yaml: "0.9"
    serde_json: "1.0"
    serde_cbor: "0.11"
